name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run tests without default features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --no-default-features --workspace
    - name: Run tests with all features
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all-features --workspace

